  name: SSH Deploy

  on:
    pull_request:
    push:
      branches:
        -current

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: SSH Deploy
          uses: easingthemes/ssh-deploy@v2.1.4
          env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
            REMOTE_USER: ${{ secrets.DEPLOY_USER }}
            REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
            SOURCE: "docs/"
            TARGET: ${{ secrets.DEPLOY_TARGET }}